[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "alembic>=1.18.4",
    "asgi-correlation-id>=4.3.4",
    "asyncpg>=0.31.0",
    "bcrypt<4.0.0",
    "cloudinary>=1.44.2",
    "fastapi[all]>=0.136.1",
    "greenlet>=3.5.0",
    "httpx>=0.28.1",
    "loguru>=0.7.3",
    "passlib[bcrypt]>=1.7.4",
    "psycopg2-binary>=2.9.12",
    "pydantic-settings>=2.14.0",
    "pytest>=9.0.3",
    "python-jose[cryptography]>=3.5.0",
    "python-multipart>=0.0.27",
    "resend>=2.30.0",
    "sentry-sdk[fastapi]>=2.59.0",
    "sqlmodel>=0.0.38",
    "uvicorn>=0.46.0",
]
